[build]
  publish = "apps/web/dist"
  # 단순화된 빌드 명령어:
  command = "pnpm install --prod=false && pnpm --filter web build && pnpm --filter api build"

[functions]
  # tsup이 직접 출력하므로 디렉토리 지정
  directory = "netlify/functions"

# [[plugins]] # 플러그인 제거
#  package = "@netlify/plugin-functions-install-core"

[context.production.environment]
  VITE_API_URL = "/.netlify/functions/api" # API 경로 확인 필요 (tsup 출력 이름 기준)
  NODE_ENV = "production"

[context.staging.environment]
  VITE_API_URL = "/.netlify/functions/api" # API 경로 확인 필요 (tsup 출력 이름 기준)
  NODE_ENV = "staging"

[[redirects]]
  from = "/api/*"
  # tsup 출력 파일 이름(api.cjs)과 일치하도록 수정
  to = "/.netlify/functions/api/:splat" 
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
