[build]
  publish = "client/dist"
  # 빌드 명령어 수정: client 패키지의 build 스크립트 사용
  command = "pnpm install --prod=false && pnpm --filter client run build && pnpm --filter api build"
  # 개발 의존성 설치를 위한 환경 변수 추가
  [build.environment]
    PNPM_FLAGS = "--production=false"
    NODE_VERSION = "18" # Node.js 버전 고정 (로그에서 18.18.0 사용 확인)

[functions]
  # tsup이 직접 출력하므로 디렉토리 지정
  directory = "netlify/functions"

# [[plugins]] # 플러그인 제거
#  package = "@netlify/plugin-functions-install-core"

[context.production.environment]
  VITE_API_URL = "/.netlify/functions/api" # API 경로 확인 필요 (tsup 출력 이름 기준)
  NODE_ENV = "production"

[context.staging.environment]
  VITE_API_URL = "/.netlify/functions/api" # API 경로 확인 필요 (tsup 출력 이름 기준)
  NODE_ENV = "staging"

[[redirects]]
  from = "/api/*"
  # tsup 출력 파일 이름(api.cjs)과 일치하도록 수정
  to = "/.netlify/functions/api/:splat" 
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
