version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nottoday-backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ECG_MODEL_PATH=/app/models/ecg_net.onnx
    restart: unless-stopped 