name: 보안 점검

on:
  schedule:
    - cron: '0 0 * * 0'  # 매주 일요일 자정에 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  security-scan:
    name: 의존성 취약점 스캔
    runs-on: ubuntu-latest
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
        
      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: pnpm 설정
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false
          
      - name: pnpm 의존성 감사
        run: |
          pnpm audit --recursive
          
      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Poetry 설정
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          
      - name: Python 의존성 감사
        run: |
          cd apps/agent
          poetry export -f requirements.txt | safety check --full-report
          
      - name: 보안 보고서 생성
        run: |
          echo "# 의존성 보안 보고서" > security_report.md
          echo "## pnpm 의존성 보고서" >> security_report.md
          pnpm audit --recursive --json | jq -r '.data.vulnerabilities | length | "발견된 취약점: \(.)"' >> security_report.md
          echo "## Python 의존성 보고서" >> security_report.md
          cd apps/agent
          poetry export -f requirements.txt | safety check --json | jq -r '.vulnerabilities | length | "발견된 취약점: \(.)"' >> ../../security_report.md
          
      - name: 보안 보고서 업로드
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: security_report.md
      
  code-scanning:
    name: 코드 스캔
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
        
      - name: CodeQL 초기화
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, typescript, python
          
      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: pnpm 설정
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false
          
      - name: pnpm 설치
        run: pnpm install
          
      - name: CodeQL 자동 빌드
        uses: github/codeql-action/autobuild@v2
        
      - name: CodeQL 분석 실행
        uses: github/codeql-action/analyze@v2
        
  dependency-review:
    name: 의존성 리뷰
    runs-on: ubuntu-latest
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
        
      - name: 의존성 리뷰
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high
          
  secret-scanning:
    name: 시크릿 스캔
    runs-on: ubuntu-latest
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
        
      - name: GitLeaks 실행
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  docker-scan:
    name: 도커 이미지 스캔
    runs-on: ubuntu-latest
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
        
      - name: Docker 설정
        uses: docker/setup-buildx-action@v2
        
      - name: API 이미지 빌드
        uses: docker/build-push-action@v4
        with:
          context: ./apps/api
          push: false
          load: true
          tags: nottoday-api:test
          
      - name: Agent 이미지 빌드
        uses: docker/build-push-action@v4
        with:
          context: ./apps/agent
          push: false
          load: true
          tags: nottoday-agent:test
          
      - name: LLM 이미지 빌드
        uses: docker/build-push-action@v4
        with:
          context: ./infra/docker
          push: false
          load: true
          tags: nottoday-llm:test
          
      - name: Trivy 스캔 - API
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nottoday-api:test
          format: 'sarif'
          output: 'trivy-api-results.sarif'
          severity: 'CRITICAL,HIGH'
          
      - name: Trivy 스캔 - Agent
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nottoday-agent:test
          format: 'sarif'
          output: 'trivy-agent-results.sarif'
          severity: 'CRITICAL,HIGH'
          
      - name: Trivy 스캔 - LLM
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nottoday-llm:test
          format: 'sarif'
          output: 'trivy-llm-results.sarif'
          severity: 'CRITICAL,HIGH'
          
      - name: Trivy 결과 업로드
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-*-results.sarif 